### ISSUE TITLE
Consider using Redux 3.1 API

### ISSUE THREAD

**Issue by gaearon** [shastajs/shasta#2]
This caught my eye:
- Easy to understand objects instead of functional composition
  - Before: `compose(applyMiddleware(middleware), devtools)(createStore)(combineReducers(reducers), initialState)`
  - After: `createStore({middleware: [], initialState: {}, reducer: fn})`

Not saying it’s perfect now, but since Redux 3.1 we allow

``` js
createStore(
  reducer,
  initialState,
  applyMiddleware(middleware)
)
```

or

``` js
createStore(
  reducer,
  initialState,
  compose(applyMiddleware(middleware), DevTools.instrument())
)
```

if you want DevTools.

Is this of any help?

**Comment by tsemerad** [comment]
I agree with this. I don't think we need a wrapper around Redux's own `createStore`.

**Comment by yocontra** [comment]
Personally I still feel like it isn't clear enough. Looking at the last block of code would require most people to open the redux docs and look at the API for createStore, compose, and applyMiddleware to figure out what's going on.

I'll update the example code to redux 3.1 and make sure we use it internally, but I still think there is value in wrapping the API. 🌴

**Comment by gaearon** [comment]
:+1:
