### ISSUE TITLE
Register 0.0.1 to NPM?

### ISSUE THREAD

**Issue by oakfang** [shastajs/shasta#3]
I know this is but a hush-hush preview, and that it's not up on NPM by design, and I applaud you for not putting up anything half-baked.

However, consider registering `shasta` anyway, just to make sure you don't end up with people having to `require('shastajs')`.

**Comment by yocontra** [comment]
Published an 0.0.1 with what's currently here so we can retain the name.

Official release will be a 1.0 release - everything until then shouldn't be used
